name: Build matador for Linux aarch64
on:
  push:
    branches:
      - workshop

jobs:
  build:
    runs-on: ubuntu-20.04
    name: build ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          aarch64-unknown-linux-gnu,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install rust toolchain
      run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
        rustup target add ${{ matrix.target }}

    - name: Install gcc-aarch64-linux-gnu
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu 

    - name: Build matador
      env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: /usr/bin/aarch64-linux-gnu-gcc
      run: cargo build --release --target ${{ matrix.target }}

    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: matador-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/matador
